import { useState } from "react";
import Expenses from "./components//Expenses/Expenses";
import NewExpense from "./components/NewExpense/NewExpense";

const DUMMY_EXPENSES = [
  {
    id: 'e1',
    title: 'Toilet Paper',
    amount: 94.12,
    date: new Date(2020, 7, 14),
  },
  { id: 'e2', title: 'New TV', amount: 799.49, date: new Date(2021, 2, 12) },
  {
    id: 'e3',
    title: 'Car Insurance',
    amount: 294.67,
    date: new Date(2021, 2, 28),
  },
  {
    id: 'e4',
    title: 'New Desk (Wooden)',
    amount: 450,
    date: new Date(2021, 5, 12),
  },
];

function App() {
  const [expenses, setExpense] = useState(DUMMY_EXPENSES);

  const addExpenseHandler = (expense) => {
    // console.log("In App.js from NewExpense.js");
    // console.log(expenses);
    setExpense((prevExpenses) => {  //return a function when depending on the previous state. prevExpenses will be automatically generated by React.
      return [expense, ...expenses];  // merge new & old expense data into an array to return
    });
  };

  return (
    <div>
      <NewExpense onAddExpense={addExpenseHandler} />
      {/* before wrapping multiple ExpenseItem components into a single Expenses component
       <Expenses
        title={expenses.title}
        amount={expenses.amount}
        date={expenses.date}
      />
      */}
      <Expenses items={expenses} />

    </div>
  );
}

export default App;
